name: checker
description: Checker is an essential tool for developers aiming to maintain the quality and organization of their software projects.
version: 1.0.0
repository: https://github.com/Jeilson-Dev/checker

environment:
  sdk: ^3.1.5

# Add regular dependencies here.
dependencies:
  path: ^1.8.0
  yaml: ^3.1.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
executables:
  checker:
